LaptoManiaOficial/Models/Secretaria.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace LaptoManiaOficial.Models
{
    public class Secretaria
    {
        [Key]
        public int Id { get; set; }
        [Required, MinLength(6), MaxLength(10)]
        public string? Ci { get; set; }
        [Required, MinLength(3), MaxLength(30)]
        [Display(Name = "Nombre de la Secretaria")]
        public string? NombreCompleto { get; set; }
        public string? Foto { get; set; }

        //manejo de foto
        [NotMapped]
        [Display(Name = "Cargar Foto")]
        public IFormFile? FotoFile { get; set; }

        //Relaciones
        public int UsuarioId { get; set;}
        public virtual Usuario? Usuario { get; set; }
    }
}

LaptoManiaOficial/Controllers/SecretariasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaptoManiaOficial.Contexto;
using LaptoManiaOficial.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;

namespace LaptoManiaOficial.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class SecretariasController : Controller
    {
        private readonly MiContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SecretariasController(MiContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Secretarias
        public async Task<IActionResult> Index(string search)
        {
            ICollection<Secretaria> secretarias;

            if (search.IsNullOrEmpty())
            {
                secretarias = await _context.Secretarias
            .Include(s => s.Usuario) // Incluye la entidad relacionada Usuario
            .OrderBy(s => s.NombreCompleto)
            .ToListAsync();
            }
            else
            {
                secretarias = await _context.Secretarias
            .Include(s => s.Usuario) // Incluye la entidad relacionada Usuario
            .Where(s => EF.Functions.Like(s.Ci, $"%{search}%") || s.NombreCompleto.Contains(search))
            .OrderBy(s => s.NombreCompleto)
            .ToListAsync();
            }

            return _context.Secretarias != null ?
                        View(secretarias) :
                        Problem("Entity set 'MiContext.Secretarias' is null.");
        }

        // GET: Secretarias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Secretarias == null)
            {
                return NotFound();
            }

            var secretaria = await _context.Secretarias
                .Include(s => s.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (secretaria == null)
            {
                return NotFound();
            }

            return View(secretaria);
        }

        // GET: Secretarias/Create
        public IActionResult Create()
        {
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "CorreoElectronico");
            return View();
        }

        // POST: Secretarias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ci,NombreCompleto,Foto,UsuarioId")] Secretaria secretaria)
        {
            if (ModelState.IsValid)
            {
                _context.Add(secretaria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "CorreoElectronico", secretaria.UsuarioId);
            return View(secretaria);
        }

        // GET: Secretarias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Secretarias == null)
            {
                return NotFound();
            }

            var secretaria = await _context.Secretarias.FindAsync(id);
            if (secretaria == null)
            {
                return NotFound();
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "CorreoElectronico", secretaria.UsuarioId);
            return View(secretaria);
        }

        // POST: Secretarias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ci,NombreCompleto,FotoFile,UsuarioId")] Secretaria secretaria)
        {
            if (id != secretaria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (secretaria.FotoFile != null)
                    {
                        await SubirFoto(secretaria);
                    }

                    _context.Update(secretaria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SecretariaExists(secretaria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "CorreoElectronico", secretaria.UsuarioId);
            return View(secretaria);
        }

        private async Task SubirFoto(Secretaria secretaria)
        {
            //formar el nombre de la foto
            string wwRootPath = _webHostEnvironment.WebRootPath;
            string extension = Path.GetExtension(secretaria.FotoFile!.FileName);
            string nombreFoto = $"{secretaria.Id}{extension}";

            secretaria.Foto = nombreFoto;

            //copiar la foto en el proyecto del servidor
            string path = Path.Combine($"{wwRootPath}/fotos/secretarias/", nombreFoto);
            var fileStream = new FileStream(path, FileMode.Create);
            await secretaria.FotoFile.CopyToAsync(fileStream);
        }

        // GET: Secretarias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Secretarias == null)
            {
                return NotFound();
            }

            var secretaria = await _context.Secretarias
                .Include(s => s.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (secretaria == null)
            {
                return NotFound();
            }

            return View(secretaria);
        }

        // POST: Secretarias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Secretarias == null)
            {
                return Problem("Entity set 'MiContext.Secretarias'  is null.");
            }
            var secretaria = await _context.Secretarias.FindAsync(id);
            if (secretaria != null)
            {
                _context.Secretarias.Remove(secretaria);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SecretariaExists(int id)
        {
            return (_context.Secretarias?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LaptoManiaOficial/Views/Secretarias/Create.cshtml
@model LaptoManiaOficial.Models.Secretaria

@{
    ViewData["Title"] = "Create";
}
<link rel="stylesheet" href="~/css/stylesCrear.css" />
<h1>Crear</h1>

<h4>Secretaria</h4>
<hr />
<div class="container-inf">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ci" class="control-label"></label>
                <input asp-for="Ci" class="form-control" />
                <span asp-validation-for="Ci" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <!--Fotos-->
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <select asp-for="UsuarioId" class ="form-control" asp-items="ViewBag.UsuarioId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger text-white">Volver al Registro</a>
</div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaptoManiaOficial/Views/Secretarias/Delete.cshtml
@model LaptoManiaOficial.Models.Secretaria

@{
    ViewData["Title"] = "Delete";
}
<link rel="stylesheet" href="~/css/stylesBorrar.css" />
<h1>Eliminar</h1>

<h3>¿Estás seguro de que quieres eliminar esta Secretaria?</h3>
<div>
    <h4>Secretaria</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ci)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ci)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.CorreoElectronico)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary text-white">Volver al Registro</a>
    </form>
</div>

LaptoManiaOficial/Views/Secretarias/Details.cshtml
@model LaptoManiaOficial.Models.Secretaria

@{
    ViewData["Title"] = "Details";
}
<link rel="stylesheet" href="~/css/stylesDetalles.css" />
<h1>Detalles</h1>

<div>
    <h4>Secretaria</h4>
    <hr />

    <div class="row">
        <div class="col-sm-4">
            @if (Model.Foto != null)
            {
                <img src="~/fotos/secretarias/@Model.Foto" class="img-thumbnail" width="150px" />
            }
        </div>
        <div class="col-sm-8">
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Ci)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Ci)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.NombreCompleto)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.NombreCompleto)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Foto)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Foto)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Usuario)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Usuario.CorreoElectronico)
                </dd>
            </dl>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-success text-white">Editar</a> 
    <a asp-action="Index" class="btn btn-danger text-white">Volver al Registro</a>
</div>

LaptoManiaOficial/Views/Secretarias/Edit.cshtml
@model LaptoManiaOficial.Models.Secretaria

@{
    ViewData["Title"] = "Edit";
}
<link rel="stylesheet" href="~/css/stylesEditar.css" />
<h1>Editar</h1>

<h4>Secretaria</h4>
<hr />
<div class="container-inf">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ci" class="control-label"></label>
                <input asp-for="Ci" class="form-control" />
                <span asp-validation-for="Ci" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoFile" class="control-label"></label>
                <input asp-for="FotoFile" class="form-control" accept="image/*" />
                <span asp-validation-for="FotoFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <select asp-for="UsuarioId" class="form-control" asp-items="ViewBag.UsuarioId"></select>
                <span asp-validation-for="UsuarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger text-white">Volver al Registro</a>
</div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaptoManiaOficial/Views/Secretarias/Index.cshtml
@model IEnumerable<LaptoManiaOficial.Models.Secretaria>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/stylesRegistros.css" />

<h1>Registro de Secretarias</h1>
<form asp-action="Index" asp-controller="Secretarias" method="get">
    <div class="row">
        <div class="col-sm-10 form-group">
            <label for="search" class="text-black">Buscar</label>
            <input name="search" id="search" class="form-control" />
        </div>
        <div class="col-sm-2">
            <button type="submit" class="btn btn-dark mt-4">Buscar</button>
        </div>
    </div>
</form>
<br />
<p>
    <a asp-action="Create">Crear nuevo Registro</a>
</p>
<div class="container-inf">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ci)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCompleto)
            </th>
      
            <th>
                Cuenta
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ci)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.CorreoElectronico)
            </td>
            <td>
                 <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success text-white">Editar</a>
                 <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info text-white">Detalles</a>
                 <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger text-white">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>