LaptoManiaOficial/Controllers/EquipoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaptoManiaOficial.Contexto;
using LaptoManiaOficial.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;

namespace LaptoManiaOficial.Controllers
{
    [Authorize]
    public class EquipoesController : Controller
    {
        private readonly MiContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EquipoesController(MiContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Equipoes
        public async Task<IActionResult> Index(string search)
        {
            ICollection<Equipo> equipos;

            if (search.IsNullOrEmpty())
            {
                equipos = await _context.Equipos
                    .OrderBy(x => x.Modelo)
                    .ToListAsync();
            }
            else
            {
                equipos = await _context.Equipos
                    .Where(x => EF.Functions.Like(x.Modelo, $"%{search}%") || EF.Functions.Like(x.Marca, $"%{search}%") || EF.Functions.Like(x.Codigo, $"%{search}%"))
                    .OrderBy(x => x.Modelo)
                    .ToListAsync();
            }

            return _context.Equipos != null ?
                        View(equipos) :
                        Problem("Entity set 'MiContext.Equipos' is null.");
        }

        // GET: Equipoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Equipos == null)
            {
                return NotFound();
            }

            var equipo = await _context.Equipos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (equipo == null)
            {
                return NotFound();
            }

            return View(equipo);
        }

        // GET: Equipoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Equipoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Codigo,Marca,Modelo,Precio,Disponibilidad,Foto")] Equipo equipo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipo);
        }

        // GET: Equipoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Equipos == null)
            {
                return NotFound();
            }

            var equipo = await _context.Equipos.FindAsync(id);
            if (equipo == null)
            {
                return NotFound();
            }
            return View(equipo);
        }

        // POST: Equipoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Codigo,Marca,Modelo,Precio,Disponibilidad,FotoFile")] Equipo equipo)
        {
            if (id != equipo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (equipo.FotoFile != null)
                    {
                        await SubirFoto(equipo);
                    }

                    _context.Update(equipo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquipoExists(equipo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipo);
        }

        private async Task SubirFoto(Equipo equipo)
        {
            //formar el nombre de la foto
            string wwRootPath = _webHostEnvironment.WebRootPath;
            string extension = Path.GetExtension(equipo.FotoFile!.FileName);
            string nombreFoto = $"{equipo.Id}{extension}";

            equipo.Foto = nombreFoto;

            //copiar la foto en el proyecto del servidor
            string path = Path.Combine($"{wwRootPath}/fotos/equipos/", nombreFoto);
            var fileStream = new FileStream(path, FileMode.Create);
            await equipo.FotoFile.CopyToAsync(fileStream);
        }

        // GET: Equipoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Equipos == null)
            {
                return NotFound();
            }

            var equipo = await _context.Equipos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (equipo == null)
            {
                return NotFound();
            }

            return View(equipo);
        }

        // POST: Equipoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Equipos == null)
            {
                return Problem("Entity set 'MiContext.Equipos'  is null.");
            }
            var equipo = await _context.Equipos.FindAsync(id);
            if (equipo != null)
            {
                _context.Equipos.Remove(equipo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EquipoExists(int id)
        {
            return (_context.Equipos?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        //PARA REPORTES
        public IActionResult ReporteEquiposDisponibles()
        {
            var equiposDisponibles = _context.Equipos.Where(e => e.Disponibilidad).ToList();
            return View(equiposDisponibles);
        }

        public IActionResult ReporteEquiposNoDisponibles()
        {
            var equiposNoDisponibles = _context.Equipos.Where(e => !e.Disponibilidad).ToList();
            return View(equiposNoDisponibles);
        }
    }
}

LaptoManiaOficial/Views/Equipoes/Create.cshtml
@model LaptoManiaOficial.Models.Equipo

@{
    ViewData["Title"] = "Create";
}
<link rel="stylesheet" href="~/css/stylesCrear.css" />
<h1>Crear</h1>

<h4>Equipo</h4>
<hr />
<div class="container-inf">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponibilidad" /> @Html.DisplayNameFor(model => model.Disponibilidad)
                </label>
            </div>
            <!--Fotos-->
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger text-white">Volver al Registro</a>
</div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaptoManiaOficial/Views/Equipoes/Delete.cshtml
@model LaptoManiaOficial.Models.Equipo

@{
    ViewData["Title"] = "Delete";
}
<link rel="stylesheet" href="~/css/stylesBorrar.css" />
<h1>Eliminar</h1>

<h3>¿Estás seguro de que quieres eliminar este Equipo?</h3>
<div>
    <h4>Equipo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponibilidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponibilidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary text-white">Volver al Registro</a>
    </form>
</div>

LaptoManiaOficial/Views/Equipoes/Details.cshtml
@model LaptoManiaOficial.Models.Equipo

@{
    ViewData["Title"] = "Details";
}
<link rel="stylesheet" href="~/css/stylesDetalles.css" />
<h1>Detalles</h1>

<div>
    <h4>Equipo</h4>
    <hr />

    <div class="row">
        <div class="col-sm-4">
            @if (Model.Foto != null)
            {
                <img src="~/fotos/equipos/@Model.Foto" class="img-thumbnail" width="150px" />
            }
        </div>
        <div class="col-sm-8">

            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Codigo)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Codigo)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Marca)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Marca)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Modelo)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Modelo)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Precio)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Precio)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Disponibilidad)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Disponibilidad)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Foto)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Foto)
                </dd>
            </dl>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-success text-white">Editar</a> 
    <a asp-action="Index" class="btn btn-danger text-white">Volver al Registro</a>
</div>

LaptoManiaOficial/Views/Equipoes/Edit.cshtml
@model LaptoManiaOficial.Models.Equipo

@{
    ViewData["Title"] = "Edit";
}
<link rel="stylesheet" href="~/css/stylesEditar.css" />
<h1>Editar</h1>

<h4>Equipo</h4>
<hr />
<div class="container-inf">
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponibilidad" /> @Html.DisplayNameFor(model => model.Disponibilidad)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="FotoFile" class="control-label"></label>
                <input asp-for="FotoFile" class="form-control" accept="image/*" />
                <span asp-validation-for="FotoFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger text-white">Volver al Registro</a>
</div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LaptoManiaOficial/Views/Equipoes/Index.cshtml
@model IEnumerable<LaptoManiaOficial.Models.Equipo>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="~/css/stylesRegistros.css" />
<h1>Equipos Registrados</h1>
<form asp-action="Index" asp-controller="Equipoes" method="get">
    <div class="row">
        <div class="col-sm-10 form-group">
            <label for="search" class="text-black">Buscar</label>
            <input name="search" id="search" class="form-control" />
        </div>
        <div class="col-sm-2">
            <button type="submit" class="btn btn-dark mt-4">Buscar</button>
        </div>
    </div>
</form>
<br />
<p>
    <a asp-action="Create">Crear nuevo Registro</a>
</p>
<div class="container-inf">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disponibilidad)
            </th>
            <!--Fotos-->
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponibilidad)
            </td>
                <!--Fotos-->
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success text-white">Editar</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info text-white">Detalles</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger text-white">Borrar</a>
                    </td>
        </tr>
}
    </tbody>
</table>
</div>

LaptoManiaOficial/Views/Equipoes/ReporteEquiposDisponibles.cshtml
@model IEnumerable<LaptoManiaOficial.Models.Equipo>

@{
    ViewData["Title"] = "equiposnodisponibles";
}

<link rel="stylesheet" href="~/css/stylesReportes.css" />

<h2>EQUIPOS DISPONIBLES</h2>
<div class="container-inf">
<table class="table">
    <thead>
        <tr>
            <th>Código</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

LaptoManiaOficial/Views/Equipoes/ReporteEquiposNoDisponibles.cshtml
@model IEnumerable<LaptoManiaOficial.Models.Equipo>

@{
    ViewData["Title"] = "equiposdisponibles";
}
<link rel="stylesheet" href="~/css/stylesReportes.css" />
<h2>EQUIPOS VENDIDOS</h2>
<div class="container-inf">
<table class="table">
    <thead>
        <tr>
            <th>Código</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
            </tr>
        }
    </tbody>
</table>
</div>